### ISSUE TITLE
Coupon functionalities working?

### ISSUE THREAD

**Issue by atlantaluck** [Deepali-AddWeb/chomchom#119]
Are the functionalities for the coupon working on the front end and the back end?

**Comment by saurabhd** [comment]
Yes, coupon functionality working for both products (Can Tho Pricing-3 month, Sang Tiem Pricing-3 month)

**Comment by denisha-addweb** [comment]
To create coupon form backend:
1. Click on Admin menu >> store >> Discounts.
2. Click on Add discount.
3. It will ask some info like
   3.1 Admin title = 'DISCOUNT_NAME'
   3.2 Choose discount type = 'Order discount' >> Its used to give Discount on total order.  
                          'Product discount' >> Its used to give Discount per product.
                          >>Select 'Product discount' out of them.
   3.3 Product discount conditions = "Apply to" >> Please select 'product(s)'
                                 "Settings" >> Add 'PRODUCT_SKU' (product sku is available from "/admin/commerce/products" sku field)
                                 "Negate" >> If checked, discount will apply on rest of the products. Please do not check it.
   3.4 Choose offer type = Please select "% off" option button. New field 'Percentage' will show up, add              your percentage of discount in that field. Ex. 20 (Do not use percentage sign along with number),
   3.5 Coupon conditions = Click on "add new coupon". New field "coupon code" will show up, fill it with your coupon code. Ex. 123456, and save it.
4. Click on "save discount".
5. Use your coupon code(Ex. 123456) in checkout process.

**Comment by atlantaluck** [comment]
Hey Saurabh, I tried 100% off for the business directory and it seem to work, but when I add featured listing to it.  It becomes from $0.00 to $30.00 instead of just $10.00 for the featured only.  

Same thing if I created coupon for Lifetime business + 1 month featured for FREE, but then instead picking 3 Months Featured.  It will add original price plus 3 months featured.

**Comment by denisha-addweb** [comment]
Can you please provide me steps to replicate this scenario? 

NOTE: I have implemented Pricing packages provided by you. 

PFA pricing package doc. 

[chomchom_scopeofwork (1).odt.zip](https://github.com/Deepali-AddWeb/chomchom/files/223561/chomchom_scopeofwork.1.odt.zip)

**Comment by atlantaluck** [comment]
Ok, I have created an automatic 100% off on 3months listing for "can tho".
1. place an ad for "can tho" "job listing for nails".
2. 1 month shows $5. 3 months shows $0.00.  Which is correct.  But if a customer picked that 3 months and they decided to also pay for 1 month of "featured listing", the price changes to $19.00.  Which is $9 for the 3months + $10 for the featured listing.  Isn't suppose to be only $10?

Thanks,

**Comment by atlantaluck** [comment]
I will test this as soon as possible.  like maybe in 1hour

**Comment by atlantaluck** [comment]
Problem still persists. here is the scenario: I've created discount !00% off for "Can Tho" 3months + 1month featured listing for FREE.
When I select 3months +1month featured it is correctly shows at $0.00, but when I changed to 3months + 2months.  Total suppose to be $10, because only $10 is being charge for the extra month of featured.

But I might think this is a good thing, since I don't want them to use that coupon and combine to get upgrade.

Please allow me sometime to think this over before I give you a straight answer to fix it or not.

Thanks,
